// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Udemy_Project_1.Data;

#nullable disable

namespace Udemy_Project_1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230706051009_AddForeignKeyTOVillaTable")]
    partial class AddForeignKeyTOVillaTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Udemy_Project_1.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("imgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("occupancy")
                        .HasColumnType("int");

                    b.Property<int>("sqft")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Villas1");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            CreatedTime = new DateTime(2023, 7, 6, 10, 40, 8, 986, DateTimeKind.Local).AddTicks(830),
                            Details = "ahbsdjcnnnnnnnnnnm jxnsjncd xjnjx",
                            Name = "Royal Villa",
                            Rate = 100.0,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            imgUrl = "httss jnc",
                            occupancy = 4,
                            sqft = 100
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "",
                            CreatedTime = new DateTime(2023, 7, 6, 10, 40, 8, 986, DateTimeKind.Local).AddTicks(847),
                            Details = "ahbsdjcnnnnnnnnnnm jxnsjncd xjnjx",
                            Name = "Royal Villa2",
                            Rate = 100.0,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            imgUrl = "httss jnc",
                            occupancy = 4,
                            sqft = 100
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "",
                            CreatedTime = new DateTime(2023, 7, 6, 10, 40, 8, 986, DateTimeKind.Local).AddTicks(850),
                            Details = "ahbsdjcnnnnnnnnnnm jxnsjncd xjnjx",
                            Name = "Royal Villa3",
                            Rate = 100.0,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            imgUrl = "httss jnc",
                            occupancy = 4,
                            sqft = 100
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "",
                            CreatedTime = new DateTime(2023, 7, 6, 10, 40, 8, 986, DateTimeKind.Local).AddTicks(853),
                            Details = "ahbsdjcnnnnnnnnnnm jxnsjncd xjnjx",
                            Name = "Royal Villa4",
                            Rate = 100.0,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            imgUrl = "httss jnc",
                            occupancy = 4,
                            sqft = 100
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "",
                            CreatedTime = new DateTime(2023, 7, 6, 10, 40, 8, 986, DateTimeKind.Local).AddTicks(855),
                            Details = "ahbsdjcnnnnnnnnnnm jxnsjncd xjnjx",
                            Name = "Royal Villa5",
                            Rate = 100.0,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            imgUrl = "httss jnc",
                            occupancy = 4,
                            sqft = 100
                        });
                });

            modelBuilder.Entity("Udemy_Project_1.Models.VillaNumber", b =>
                {
                    b.Property<int>("VillaNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpclDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("VillaNo");

                    b.HasIndex("VillaId");

                    b.ToTable("VillaNumber");
                });

            modelBuilder.Entity("Udemy_Project_1.Models.VillaNumber", b =>
                {
                    b.HasOne("Udemy_Project_1.Models.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });
#pragma warning restore 612, 618
        }
    }
}
