// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Udemy_Project_1.Data;

#nullable disable

namespace Udemy_Project_1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230705045111_NewVillaTable")]
    partial class NewVillaTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Udemy_Project_1.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("imgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("occupancy")
                        .HasColumnType("int");

                    b.Property<int>("sqft")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            CreatedTime = new DateTime(2023, 7, 5, 10, 21, 11, 571, DateTimeKind.Local).AddTicks(9173),
                            Details = "ahbsdjcnnnnnnnnnnm jxnsjncd xjnjx",
                            Name = "Royal Villa",
                            Rate = 100.0,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            imgUrl = "httss jnc",
                            occupancy = 4,
                            sqft = 100
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "",
                            CreatedTime = new DateTime(2023, 7, 5, 10, 21, 11, 571, DateTimeKind.Local).AddTicks(9190),
                            Details = "ahbsdjcnnnnnnnnnnm jxnsjncd xjnjx",
                            Name = "Royal Villa2",
                            Rate = 100.0,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            imgUrl = "httss jnc",
                            occupancy = 4,
                            sqft = 100
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "",
                            CreatedTime = new DateTime(2023, 7, 5, 10, 21, 11, 571, DateTimeKind.Local).AddTicks(9259),
                            Details = "ahbsdjcnnnnnnnnnnm jxnsjncd xjnjx",
                            Name = "Royal Villa3",
                            Rate = 100.0,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            imgUrl = "httss jnc",
                            occupancy = 4,
                            sqft = 100
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "",
                            CreatedTime = new DateTime(2023, 7, 5, 10, 21, 11, 571, DateTimeKind.Local).AddTicks(9262),
                            Details = "ahbsdjcnnnnnnnnnnm jxnsjncd xjnjx",
                            Name = "Royal Villa4",
                            Rate = 100.0,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            imgUrl = "httss jnc",
                            occupancy = 4,
                            sqft = 100
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "",
                            CreatedTime = new DateTime(2023, 7, 5, 10, 21, 11, 571, DateTimeKind.Local).AddTicks(9265),
                            Details = "ahbsdjcnnnnnnnnnnm jxnsjncd xjnjx",
                            Name = "Royal Villa5",
                            Rate = 100.0,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            imgUrl = "httss jnc",
                            occupancy = 4,
                            sqft = 100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
